import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation, PresentationFile} from '@oai/artifact-tool';
const root=path.resolve(process.cwd());
const skill=process.env.PANTRY_PRESENTATION_SKILL;
if(!skill)throw new Error('Set PANTRY_PRESENTATION_SKILL to the installed Codex presentations skill directory.');
const {finalizePresentation,resolvePresentationFont}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')).href);
const font=resolvePresentationFont({fontFamily:'Arial',availableFonts:['Arial','Georgia']});
const serif='Georgia';
const C={green:'#173E32',cream:'#F5F3E9',lime:'#D9ED9C',ink:'#23372D',muted:'#657267'};
const p=Presentation.create({slideSize:{width:1280,height:720}});
function text(s,value,x,y,w,h,size=32,color=C.ink,bold=false,family=font){const sh=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});sh.text=value;sh.text.style={typeface:family,fontSize:size,color,bold,autoFit:'none'};return sh;}
function slide(bg=C.cream){let s=p.slides.add();s.background.fill=bg;return s;}
function footer(s,n,dark=false){text(s,`PANTRY RELAY    /    SHIVAM GUPTA`,64,666,880,25,15,dark?'#B7C8BB':C.muted);text(s,String(n).padStart(2,'0'),1160,666,56,25,15,dark?'#B7C8BB':C.muted);}
function notes(s,value){s.speakerNotes.textFrame.setText(value);}
async function screenshot(s,file,x,y,w,h){try{let blob=new Uint8Array(await fs.readFile(path.join(root,'artifacts/screenshots',file)));s.images.add({blob,contentType:'image/png',alt:`Actual Pantry Relay ${file.replace('.png','')} screenshot with fictitious sample data`,fit:'contain',position:{left:x,top:y,width:w,height:h}});}catch{throw new Error('Required screenshot missing: '+file);}}
let s=slide(C.green);text(s,'PANTRY RELAY',68,65,950,36,20,C.lime,true);text(s,'Make the food\nalready here\ngo further.',62,148,1150,300,82,C.cream,false,serif);text(s,'Surplus coordination for a trusted pantry network',68,486,1080,62,31,C.cream);text(s,'Shivam Gupta\nHack Away Hunger 2026',68,580,900,68,22,'#B7C8BB');notes(s,'Project lead: Shivam Gupta. AI-assisted development is disclosed in CREDITS.md. This presentation describes an implemented supervised-pilot release, not validated adoption. Opening: Imagine opening a pantry tomorrow with a produce gap while another pantry has approved surplus.');
s=slide();text(s,'Coordination at network scale',64,58,1140,78,46,C.ink,false,serif);text(s,'700',64,170,650,180,140,C.green);text(s,'partners and programs across 55 Iowa counties',76,344,1080,70,32,C.ink);text(s,'Food Bank of Iowa describes a network large enough to make\ncoordination matter. The unanswered question is how often\none pantry’s approved surplus can fill another’s next-service gap.',76,450,1100,142,27,C.muted);text(s,'Source: Food Bank of Iowa, FY2025 Impact Report. No partnership implied.',76,613,1100,28,17,C.muted);footer(s,2);notes(s,'Source: https://foodbankiowa.org/app/uploads/2025/08/FY_2025_impact_report_v8.pdf accessed2026-09-22. The scale statistic establishes context, not frequency of mismatch or market demand. We have not conducted operator interviews.');
s=slide();text(s,'A shortfall before tomorrow’s service',64,58,1150,80,45,C.ink,false,serif);text(s,'Cedar Grove',68,184,540,55,37,C.green,true);text(s,'Produce above its own protected reserve',70,253,490,96,28,C.muted);text(s,'Eastside',694,184,510,55,37,C.green,true);text(s,'An upcoming service needs\n120 lb of produce',696,253,488,96,28,C.muted);text(s,'A useful transfer needs more than a match.',68,421,1140,68,41,C.ink,false,serif);text(s,'The receiving pantry must agree. Transport must fit.\nSomeone must record the pounds actually accepted.',70,513,1080,85,28,C.muted);text(s,'Illustrative scenario. All pantry names and operating data are fictitious.',70,618,1100,27,17,C.muted);footer(s,3);notes(s,'Tell the fictional scenario clearly. Source pantry protected reserve ensures its visitors are not deprioritized. This product does not decide assistance eligibility or collect household identities.');
s=slide();text(s,'An explainable transfer proposal',64,42,1130,64,43,C.ink,false,serif);await screenshot(s,'planner.png',58,122,1164,487);text(s,'Review the food, quantities and constraints before reserving stock.',66,619,1100,31,23,C.muted);footer(s,4);notes(s,'This is a screenshot of the running application with fictitious data. Live demo: generate plan, inspect reasons, reserve produce transfer. Matching is deterministic greedy allocation, not globally optimized road routing. Great-circle distance is a rough screening measure.');
s=slide(C.green);text(s,'The receipt is the outcome',64,57,1140,80,48,C.cream,false,serif);text(s,'120 lb',67,199,560,128,96,'#A9BEB1');text(s,'dispatched',74,333,520,46,29,'#A9BEB1');text(s,'112 lb',674,199,535,128,96,C.lime);text(s,'accepted at the destination',679,333,532,72,28,C.cream);text(s,'8 lb damaged. The missing quantity reopens the need.',70,468,1110,84,35,C.cream);text(s,'Illustrative partial receipt. Accepted weight is not a count of meals or people fed.',73,595,1100,48,21,'#B7C8BB');footer(s,5,true);notes(s,'Demo values120 dispatched,112 accepted,8 rejected. Only accepted weight enters throughput; late delivery does not fulfill a missed service. Received inventory is protected by default. Full rejection records0 and a reason. These values are sample outcomes, not real impact.');
s=slide();text(s,'A complete handoff record',64,44,1150,70,45,C.ink,false,serif);await screenshot(s,'impact.png',58,132,1164,465);text(s,'Authenticated actions, stock reservations, receipt differences and an exportable audit trail.',66,611,1110,48,23,C.muted);footer(s,6);notes(s,'Running product screenshot. Controls include network isolation, coordinator/driver roles, CSRF, opaque cookie sessions, integer weight arithmetic and atomic writes. Audit is API append-only but not tamperproof against a database admin. Operator records confirmations; no independently verified nonprofit identity or signature claim.');
s=slide();text(s,'A proposed business model',64,57,1130,78,46,C.ink,false,serif);text(s,'$149',64,177,650,158,124,C.green);text(s,'per network / month',76,345,1080,57,35,C.ink);text(s,'Up to 10 pantry sites. Free self-hosting.\nA six-week supervised pilot comes first.',76,440,1080,91,30,C.muted);text(s,'At a hypothetical $25/hour staff cost, the price requires\nabout 6 hours saved per month to justify itself on time alone.',76,568,1095,68,24,C.muted);footer(s,7);notes(s,'Pricing is an unvalidated hypothesis, no customers or revenue claimed. Buyer: regional pantry-network coordinator, not people receiving food. Illustrative monthly economics149 revenue,15 allocated hosting/backup,30 support labor,104 contribution before overhead. No payment collection implemented.');
s=slide();text(s,'Six weeks to test the real value',64,57,1140,78,46,C.ink,false,serif);text(s,'01',68,176,110,65,47,C.green);text(s,'Baseline',205,177,930,50,36,C.ink,true);text(s,'Observe existing transfers, entry effort and service gaps.',205,240,930,57,27,C.muted);text(s,'02',68,331,110,65,47,C.green);text(s,'Three pantries, one coordinator',205,332,950,52,36,C.ink,true);text(s,'Run approved transfers with existing transport and clear safety ownership.',205,395,950,74,27,C.muted);text(s,'03',68,504,110,65,47,C.green);text(s,'A continuation decision',205,504,950,52,36,C.ink,true);text(s,'Compare category gaps, staff time, transport effort and accepted weight.',205,568,950,62,27,C.muted);footer(s,8);notes(s,'Proposed pilot, not recruited. Six weeks: baseline week1; supervised weeks2-5; evaluation week6. Targets must be agreed before start. Suggested25% lower coordination time,20% lower category gap,95% receipts complete. Small uncontrolled pilot cannot establish causal household food insecurity reduction.');
s=slide(C.green);text(s,'THE NEXT STEP',68,71,1090,35,21,C.lime,true);text(s,'One network.\nA real operating test.',64,181,1145,205,67,C.cream,false,serif);text(s,'We’re looking for a coordinator and three pantries\nto test whether the next service can be better supplied.',73,445,1120,108,32,C.cream);text(s,'Pantry Relay  /  Shivam Gupta\ngithub.com/shi1720/Hack-Away-Hunger',73,588,1100,67,22,'#B7C8BB');notes(s,'Close with a modest concrete ask. Do not claim a signed pilot or partners. Eligibility and attendance are participant responsibilities outlined in submission/START-HERE.md.');
await fs.mkdir(path.join(root,'tmp/slides/rendered'),{recursive:true});
const candidate=path.join(root,'tmp/slides/candidate.pptx');
await(await PresentationFile.exportPptx(p)).save(candidate);
for(let i=0;i<p.slides.items.length;i++){const blob=await p.export({slide:p.slides.items[i],format:'png',scale:1.5});await fs.writeFile(path.join(root,'tmp/slides/rendered',`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await blob.arrayBuffer()));}
const finalPath=path.join(root,'output',process.env.PANTRY_PITCH_FILENAME || 'Pantry-Relay-Pitch.pptx');
await fs.mkdir(path.join(root,'.codex-finalizer'),{recursive:true});
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath,pythonExecutable:process.env.PANTRY_ARTIFACT_PYTHON || 'python3',integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],requiredNativeTableOwnerSlides:[],fontPolicy:{basis:'design',families:[font,serif]},verifyArtifactToolImport:true,receiptPath:path.join(root,'.codex-finalizer/pitch.validation.json')});
console.log(finalPath);
